INSERT INTO `bazadanychduszka`.`grupy` (`Nazwa Grupy`) VALUES ('L01');
INSERT INTO `bazadanychduszka`.`grupy` (`Nazwa Grupy`) VALUES ('L02');
INSERT INTO `bazadanychduszka`.`grupy` (`Nazwa Grupy`) VALUES ('L03');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('architektura');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('automatyka i robotyka');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('bezpieczeństwo wewnętrzne');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('biotechnologia');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('budownictwo');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('elektronika i telekomunikacja');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('elektrotechnika');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('energetyka');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('europeistyka');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('finanse i rachunkowość');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('fizyka techniczna');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('informatyka');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('inżynieria materiałowa');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('inżynieria środowiska');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('logistyka');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('lotnictwo i kosmonautyka');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('matematyka');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('mechanika i budowa maszyn');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('mechatronika');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('ochrona środowiska');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('stosunki międzynarodowe');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('technologia chemiczna');
INSERT INTO `bazadanychduszka`.`kierunki` (`Nazwa kierunku`) VALUES ('zarządzanie i marketing');
INSERT INTO `bazadanychduszka`.`stopnie` (`Nazwa stopnia`) VALUES ('Adiunkt');
INSERT INTO `bazadanychduszka`.`stopnie` (`Nazwa stopnia`) VALUES ('Asystent');
INSERT INTO `bazadanychduszka`.`stopnie` (`Nazwa stopnia`) VALUES ('Doktorant');
INSERT INTO `bazadanychduszka`.`tryby` (`Nazwa trybu`) VALUES ('Stacjonarny');
INSERT INTO `bazadanychduszka`.`tryby` (`Nazwa trybu`) VALUES ('Niestacjonarny');
INSERT INTO `bazadanychduszka`.`semestry` (`Numer Semestru`) VALUES ('1');
INSERT INTO `bazadanychduszka`.`semestry` (`Numer Semestru`) VALUES ('2');
INSERT INTO `bazadanychduszka`.`semestry` (`Numer Semestru`) VALUES ('3');
INSERT INTO `bazadanychduszka`.`semestry` (`Numer Semestru`) VALUES ('4');
INSERT INTO `bazadanychduszka`.`semestry` (`Numer Semestru`) VALUES ('5');
INSERT INTO `bazadanychduszka`.`semestry` (`Numer Semestru`) VALUES ('6');
INSERT INTO `bazadanychduszka`.`semestry` (`Numer Semestru`) VALUES ('7');
INSERT INTO `bazadanychduszka`.`semestry` (`Numer Semestru`) VALUES ('8');
INSERT INTO `bazadanychduszka`.`ocenydef` (`Wartosc`) VALUES ('2.0');
INSERT INTO `bazadanychduszka`.`ocenydef` (`Wartosc`) VALUES ('2.5');
INSERT INTO `bazadanychduszka`.`ocenydef` (`Wartosc`) VALUES ('3.0');
INSERT INTO `bazadanychduszka`.`ocenydef` (`Wartosc`) VALUES ('3.5');
INSERT INTO `bazadanychduszka`.`ocenydef` (`Wartosc`) VALUES ('4.0');
INSERT INTO `bazadanychduszka`.`ocenydef` (`Wartosc`) VALUES ('4.5');
INSERT INTO `bazadanychduszka`.`ocenydef` (`Wartosc`) VALUES ('5.0');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Administracja systemów bazodanowych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Administracja systemów rozproszonych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Aerodynamika');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Agroekologia');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Algebra liniowa');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Algebra ogólna i teoria liczb');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Algorytmy i struktury danych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Analiza danych pomiarowych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Analiza matematyczna');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Aplikacje internetowe');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Architektura systemów komputerowych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Arkusze kalkulacyjne w finansach i rachunkowości');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Aspekty organizacyjno prawne rynku OZE');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Audyt bezpieczeństwa');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Audyt energetyczny budynków');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Automatyka');