INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Administracja systemów bazodanowych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Administracja systemów rozproszonych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Aerodynamika');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Agroekologia');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Algebra liniowa');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Algebra ogólna i teoria liczb');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Algorytmy i struktury danych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Analiza danych pomiarowych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Analiza matematyczna');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Aplikacje internetowe');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Architektura systemów komputerowych');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Arkusze kalkulacyjne w finansach i rachunkowości');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Aspekty organizacyjno prawne rynku OZE');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Audyt bezpieczeństwa');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Audyt energetyczny budynków');
INSERT INTO `bazadanychduszka`.`przedmioty` (`Nazwa przedmiotu`) VALUES ('Automatyka');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '12', `wykladowcyid` = '1' WHERE (`przedmiotID` = '1');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '12', `wykladowcyid` = '1' WHERE (`przedmiotID` = '2');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '16', `wykladowcyid` = '2' WHERE (`przedmiotID` = '3');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '20', `wykladowcyid` = '3' WHERE (`przedmiotID` = '4');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '11', `wykladowcyid` = '4' WHERE (`przedmiotID` = '5');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '17', `wykladowcyid` = '4' WHERE (`przedmiotID` = '6');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '6', `wykladowcyid` = '5' WHERE (`przedmiotID` = '8');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '12', `wykladowcyid` = '4' WHERE (`przedmiotID` = '9');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '12', `wykladowcyid` = '6' WHERE (`przedmiotID` = '10');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '10', `wykladowcyid` = '7' WHERE (`przedmiotID` = '12');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '23', `wykladowcyid` = '7' WHERE (`przedmiotID` = '13');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '3', `wykladowcyid` = '8' WHERE (`przedmiotID` = '14');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '3', `wykladowcyid` = '8' WHERE (`przedmiotID` = '15');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '2', `wykladowcyid` = '9' WHERE (`przedmiotID` = '16');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '12', `wykladowcyid` = '1' WHERE (`przedmiotID` = '7');
UPDATE `bazadanychduszka`.`przedmioty` SET `kierunekid` = '12', `wykladowcyid` = '10' WHERE (`przedmiotID` = '11');